parameters:
#    mobile_frontend.example.class: Mobile\FrontendBundle\Example

services:
#    mobile_frontend.example:
#        class: %mobile_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

services:
    ens.jobeet.admin.gallery:
        class: Mobile\FrontendBundle\Admin\GalleryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: gallery, label: Gallery }
        arguments: [null, Mobile\FrontendBundle\Entity\gallery, MobileFrontendBundle:GalleryAdmin]