parameters:
#    mobile_frontend.example.class: Mobile\FrontendBundle\Example

services:
#    mobile_frontend.example:
#        class: %mobile_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
